### ISSUE TITLE
Cell tracking whitelist

### ISSUE THREAD

**Issue by dimethylglymaxim** [SchmollerLab/Cell_ACDC#127]
I think it would be useful to have such feature, for convenient tracking and measuring individual cell inside of a big group, for example.

**Comment by ElpadoCan** [comment]
Hi dimethylglymaxim,

I am not sure I understood correctly. You would like to be able to track only specific cells and not bother with errors on other cells? Could you please elaborate on that with an example? Thank you very much!

**Comment by dimethylglymaxim** [comment]
Yes, you are correct - I`m looking for something like "annotate all cells as removed from analysis, except ... (id=1, 2, 6)". In that case, I indeed will correct only the cells that I'm interested in. Or it could be something like "remove all segmentation labels, except...".

**Comment by dimethylglymaxim** [comment]
For example, I would like to track only the mother cell, which is budding rapidly.  This function should utilize 3-4 clicks, when manual annotating can take up to 100 for all daughter cells on a hundreds of frames.

**Comment by ElpadoCan** [comment]
You are not the first one to ask for this, so I think it's time we think about how to implement it. However, this can be quite dangerous. 

If you are talking about cell cycle annotations then I think it is doable. Because the software can delete all the cells with ID 1 for example only if tracking is correct. If tracking is wrong, then it will delete cell ID 1 which is not the cell you wanted to delete. 

However, you need to be careful, we often realize tracking or segmentation errors only during cell cycle annotations, but if you deleted the wrong cells (because of tracking error you would not realize).

Anyway, I think it can be useful in many situations, but we need to decide how it should work.

For your "only mother" let me write an hypothetical example to be sure I understood correctly:

1. You have a mother cell with ID 1 that buds and generate bud ID 2.
2. Bud ID then will bud again and generate bud ID 3.
3. In the meantime, cell ID 1 is budding again and generates bud ID 4.

In this example, you would like to say "ignore the buds of cell ID 2 (so ignore ID 3), I am interested only in the buds of cell ID 1", right?

If this is what you are talking about, what are the problems you get when you try to ignore the other cells?

**Comment by dimethylglymaxim** [comment]
I'm sorry for not being completely clear. 
In example, provided by you, I would ignore all the cells, except ID 1 (or "track only ID 1"). Basically, like this:

before "ignore all, except ...":
![image](https://user-images.githubusercontent.com/111124664/184379477-32ca0cfb-f22a-45ea-b921-6c8f77b50e29.png)

after "ignore all, except ...":

![image](https://user-images.githubusercontent.com/111124664/184379758-6823dc06-7724-4155-9a0b-431b49a466b9.png)

**Comment by ElpadoCan** [comment]
No problem at all, I just need to be sure we are implementing the right feature.

So in that example, you would like the software to not bother you with errors about the excluded cells or do you simply want a way to annotate as excluded "all cells except ID 1"? 

Because at the moment, as you could see, you can annotate cells as excluded but they are still tracked. This is required because exclusion goes by ID. So let's suppose cell ID 3 in frame 5 gets the wrong ID 10 (because of a tracking error), now the software doesn't know that what you want to exclude is actually ID 10, but it goes and excludes cell ID 3 (which was given to another cell, that you might not want to exclude). Do you see the problem? To actually exclude the right cell you first need to edit ID 10 and assign ID 3 to it. This means that cell ID 3 still requires tracking.

If instead, you first correct tracking and then you want to do cell cycle analysis of a subset of cells that is probably more straightforward to do.

With this being said we can implement whatever feature you want of course, I just need to understand what could actually work well.

**Comment by ElpadoCan** [comment]
Also this might be related #125
