### ISSUE TITLE
Timecourse data structure

### ISSUE THREAD

**Issue by ewabb** [SchmollerLab/Cell_ACDC#175]
Hi,
I'm not sure how to save my .tif files given that I have multiple channels, positions, and a timecourse (all in single-channel individual .tiffiles). Even when I only work with the files from a single position, the 'Create data structure from microscopy files' does not allow for a timecourse. It either tries to force multiple sites or gives an error when I set up number of timepoints correctly. Can the ADCC work correctly with a timecourse in multiple channels?

**Comment by ElpadoCan** [comment]
Hi @ewabb, I'm happy to hear you want to try out Cell-ACDC! 

You can definitely work with timecourse data with multiple channels, this is how I use Cell-ACDC on a daily basis. 

However, it needs to be structured in a specific way. Essentially you need to have one .tif file per position per channel. So let's suppose you have three channels, 10 positions and 150 frames per channel. In this example, you are going to need 30 .tif files, 3 channels per position. The single .tif file will be a single-channel multi-page .tif file with 150 frames, so essentially a series of 150 2D  images (or 3D if you have z-stacks). Each file should have the same basename (typically the name of the microscopy file) plus a text that allows you to identify which file is which channel. 

Achieving this manually is tedious, which is why we have the `Create data structure from microscopy files` module.

If I understood correctly you have multiple .tif files where a single file contains a single-channel time course data, right? Do you have one such file for each position or does the file also contain the positions? Because if you already have one .tif file per position per channel it sounds like you already have the correct structure and you "only" need to put it into Position folders. I can write a small utility for that.

However, the fastest way would be that I test with your data, if possible. You can share it with me on Google Drive to my email padovaf@tcd.ie or you can use any other cloud service you want.

Let me know what you prefer, thanks! 

Cheers,
Francesco

**Comment by ElpadoCan** [comment]
Hi, @ewabb I received your data and I will test it soon! I will keep you updated! 

PS: Sorry for the late replies but you seem to be in a different time zone (I'm in Germany). 

Cheers,
Francesco

**Comment by ElpadoCan** [comment]
Hi @ewabb, so I looked at your data and I have a couple of questions:

1. Are these the files produced by the microscope or are the files you processed with MATLAB?
2. If I understood correctly the file `3_4_2_Hoechst_1.tif` is the first time point of a specific position of the Hoechst channel (do the numbers 3_4_2 have a meaning? I guess they identify a position?), while the file `3_4_2_reporter_1.tif` is the first time point of the same position but different channel? So then,  `3_8_1_Hoechst_1.tif` is the first time point of the channel  `Hoechst` but different position?

Because I could easily make a utility to correctly structure the data given what you sent me, but I would prefer to start from the raw microscopy files, if possible. How big are they? 

One of the advantages of using the raw microscopy files directly as input for the `Create data structure from microscopy files` module is that this module can also read the metadata of the image, like the pixel size, the number of frames, the frame interval etc. (if they are available in the microscopy file of course). 

So far, we never had to work with microscopy files separated by time-point, so we definitely need to implement something for your data, but I can do it pretty easily.

Please, let me know what you think, and if you can share a sample of microscopy files. Have a good weekend! 

Cheers,
Francesco

**Comment by ewabb** [comment]
Hi Francesco,
sorry for not replying here earlier. Thank you so much for your prompt reply and willingness to help! 
Yes, you are correct, I have multiple .tif files, separated by position and channel. In your example, that is 10 positions x 150 frames x 3 channels = 4500 images. The microscope produces images separated in different folders by the time point, then I rename and reorganize them using a custom script in MATLAB (so I can change the naming if that is the issue). I am sharing sample files from 3 sites (the first three numbers are row, column and site on the plate), 2 channels (Hoechst/reporter), 5 time points (last number). Your understanding of the naming is correct. 
I'm going to share 3 time point folders produced by the microscope with you now for comparison. Either way works with me. 

Best,
Ewa

**Comment by ewabb** [comment]
Also, in some experiments the run will be paused and restarted, which results in multiple folders, each with its Timepoint folders that need to be stitched together

**Comment by ElpadoCan** [comment]
Hi Ewa, perfect I got it. I will add this type of data structure to the Cell-ACDC data structure module. I will keep you updated! 

Cheers,
Francesco

**Comment by ElpadoCan** [comment]
Hi Ewa,

In the end, I decided to go for the structure of the files you created with MATLAB because I think it is a good pattern that can be useful also to other users dealing with files separated by time-point.

I released `v1.2.4rc48` with the new feature. To use it, run the module `0. Create data structure from microscopy/image file(s)...` and then, instead of Bio-Formats, choose "Re-structure". From there follow the instructions in the pop-up windows, I hope they are clear enough.

To install the latest version, please, activate the acdc environment and then install with the command `pip install --upgrade cellacdc`.

Let me know if it works! Thanks.

Cheers,
Francesco

**Comment by ewabb** [comment]
Thanks Francesco, I'll let you know how it went!

**Comment by ewabb** [comment]
It works, thanks! If I may have a request for further update, would it be possible to add additional channels to a time course that only have one time point? If you have an additional channel that has a stable expression and only want to measure it once or do a staining at the end of the experiment and correlate the data with live traces in the same cells, that would be very powerful. Thanks!

**Comment by ElpadoCan** [comment]
Ok great! I will close this issue then and open a new one with the new request ok? It's easier for me to keep track of things this way. I created the new issue #182, see you there! 

Cheers,
Francesco
