### ISSUE TITLE
Segmentation of multichannel tiff differ between ACDC and Cellpose

### ISSUE THREAD

**Issue by dfgdgdfgd** [SchmollerLab/Cell_ACDC#177]
Hi Francesco,

i segmented a combined 3D multichannel tiff (488nm for a cytoplasmatic marker (YAP) and 650nm for nuclei) using the native Cellpose GUI and ACDC and the results differ significantly in particular the cytoplasm results. Maybe because in ACDC one can not choose the option to define channel 2 (which is in most cases the nuclei channel)?
 Should i send you the 3D data used?

Thanks and best
Mario

![image](https://user-images.githubusercontent.com/116281469/198543440-cf7bab50-7287-496e-b8fc-b39f46acf6ff.png)

**Comment by ElpadoCan** [comment]
HI Mario, beautiful image! 

Anyway, you are right, cellpose in ACDC doesn't support the second channel yet. I will create an issue for that and I will work on it in the next few days, cool idea! 

If you can send me the data (zip the Position you are testing with) it would be great because I can compare the results before releasing the upgrade, thanks! 

PS: I am almost done with the feature described in #170 

Cheers,
Francesco

**Comment by dfgdgdfgd** [comment]
Hi Francesco,

thanks, i sent you the data via email.

Great to hear, that the new feature is already finished, looking forward to it!! ;)

**Comment by ElpadoCan** [comment]
Hi Mario, 

I released `v1.2.4rc48` where I added the possibility to segment with a second channel using cellpose in Cell-ACDC. You simply have another list selector in the cellpose parameters window where you select which one should be the second channel.

Please, activate the `acdc` environment and then install the latest version with the command `pip install --upgrade cellacdc`.

Let me know if it works!

**Comment by ElpadoCan** [comment]
Great, I will close both this and issue #178 then. Feel free to reopen them if needed! 

Cheers,
Francesco
