### ISSUE TITLE
Quick skip to the next position.

### ISSUE THREAD

**Issue by dimethylglymaxim** [SchmollerLab/Cell_ACDC#241]
### Description:

Hi there!

I think it would be useful to be able to quickly switch to the next position in the experiment folder without the need to open explorer pop-ups.
For example, I have an experiment folder, with 50 positions with the same parameters (one position for each time lapse). Between each position, I have to go through each step of loading (choosing the same directory, same parameters, channels, etc.). I think this might be nice little quality of life feature.

Cheers,
Max

**Comment by ElpadoCan** [comment]
Hi Max,

I hope you had a good start to the year! 

Anyway, that's a good idea! 

Just a small question, at the moment it is already possible to load multiple NON-timelapse positions and easily scroll between them. However, this is possible only because a NON-timelapse position is typically way smaller than a timelapse one. So for timelapse, I would not load all the positions into memory (I doubt 50 positions would anyway fit into the RAM), but rather I would add a selector that allows you to load a specific position without going through the standard loading process. You would still need to wait until the position is loaded though. Would that be ok with you? 

Let me know what you think about it, thanks! 

Cheers,
Francesco

**Comment by dimethylglymaxim** [comment]
Yes, that is exactly what I need!
Thank you very much, I hope you had a great vacation too!
Also, I think it would be wise to still ask to save before moving to the next position)

Cheers,
Max

**Comment by ElpadoCan** [comment]
Oh yeah you are right it should still ask to save thanks for pointing that out!

**Comment by dimethylglymaxim** [comment]
This function also would look nice in the dataprep module:D

**Comment by ElpadoCan** [comment]
True, good idea. I'm running the last tests and I will release this evening

**Comment by ElpadoCan** [comment]
Hi Max, 

I just released `v1.2.4rc57` with the feature you requested.

There is now a new entry in the File menu of the main GUI (and of the data prep module) called `Load a different position...`. The shortcut for this is `Shift+P` (which might stand for "Shift Position" :D).

When you trigger this you get a widget where you select which position you want to load. After deciding whether to save or not before switching, the GUI will go into auto-pilot mode where the dialogues still appear but the button corresponding to the last choice you made is automatically clicked and the dialogue closed. Same story for the data prep gui.

I hope it is what you had in mind, otherwise let me know how you would change it.

To update, activate the `acdc` environment and run the command `pip install --upgrade cellacdc`.

Let me know if it works and have a good weekend! 

Cheers,
Francesco

**Comment by dimethylglymaxim** [comment]
Clever!)

Thank you, looks fine for me.

Cheers, 
Max
