### ISSUE TITLE
How to restore right side image?

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#27]
A sort of silly question--I used the right click menu to disable the right image that has the pixel masks, but now I'm not sure how to restore it. Restarting ACDC didn't bring it back. Is it in the menu somewhere?

**Comment by ElpadoCan** [comment]
Hi Jordan, you can get the same right click menu when you right click on the right side colorbar (same for the left side colorbar). Those colorbars are there because you can access that menu also if you have tools active because there is no interaction of a tool with the colorbar. Let me know if it works. Thanks!

**Comment by jordanyx** [comment]
Ah I tried right-clicking everywhere but not on the bar itself, thank you!
