### ISSUE TITLE
Question about data prep module

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#28]
Has the behavior of the data prep module been updated recently?

I recently noticed that the data prep module now generates some new files: {ch_name}_aligned.npz. In addition, the tif files for each channel now reflect the aligned versions, where previously it was the "raw" unshifted versions.

This isn't a problem, I just wanted to check and make sure this is expected behavior; it's complicated the process of retroactively adding channels in some instances, but it's a very temporary issue specific to my situation.

**Comment by ElpadoCan** [comment]
Hi Jordan,

Yes both the .tif and the aligned contains the exact same data.

The reason why we keep the .tif is because they are a common file format that one can still visualize in any image viewer. However, I never tried, but they should be redundant and ignored by ACDC because it always looks for the aligned file and stop searching once found. I'm pretty sure they are not needed anymore.

For adding a channel, I agree, it's not straightforward because I never thought of it as a routine operation. However, if you need to do it often we can think of a new feature to add channels automatically.

Where do you add new channels from? From a microscopy file?

**Comment by jordanyx** [comment]
Hi Francesco,

Yeah, I concede it's something one shouldn't really have to do if using the pipeline normally—it came about because I was trying to add a version of a channel that had some pre-processing (flatfield background subtraction) done on it prior to running it through the ACDC pipeline, but I had already done all the other steps for that position, so I didn't want to start over. In other words, I wanted to use the same masks to run quantifications on an additional fluorescence channel added retroactively.

My current strategy has been deleting the align-shifted tifs and npz files in the Images folder, removing the segm.npz file (so I don't get the popup about zipping), putting the original unshifted tifs for each channel back in manually, then running data prep again (and also updating the metadata csv). Then I reopen in the GUI and save with measurements, and that seems to work fine for my current purposes.

I don't think being able to add a new channel for quantification is a bad thing, but it's also quite niche, so I wouldn't ask you to add a feature like that unless other people also have use for it. Thanks for confirming how Data Prep is supposed to work!
