### ISSUE TITLE
Improved reassignment of mother/bud?

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#29]
When doing cell cycle annotations for mother/bud pairs, sometimes I run into a bud that is assigned to the wrong mother due to proximity to another cell. When I try to manually reassign, it's often a messy process of going into the "edit annotations" table and trying to get the right ratio of S/G2/M to G1 to mother to bud cells. It would be nice if the appropriate changes to the table could be automated some way, and then that would be propagated to subsequent frames (whereas currently I have to do every frame manually until division).

Of course if there's already a tool to make this easier, please just point me in the right direction! None of the toolbar stuff seems to help with this right now.

**Comment by ElpadoCan** [comment]
Hi Jordan, technically, automating mother-bud pairing correction it's the super main feature of Cell-ACDC and probably the first thing we ever implemented 😁 so I feel there is something else going on.

We annotated many videos and we never had to manually edit the table. Did you try to just reassign the bud to another mother? It should automatically correct past and future frames, and if it can't it should tell you why.

To assign a bud to another mother, activate the relative button (which actually has the same icon as Cell-ACDC itself, because this is the main feature) then right click on the bud and then right click on the correct mother. Let me know if it works, thanks!

**Comment by jordanyx** [comment]
Hi Francesco,

When I try doing that, I usually get a popup saying I can't assign that cell as a mother mother because it's in G1, so then I go to the annotations table to change its phase to S, which leads to another popup saying there's a mismatch between the number of mothers and buds. So, I end up having to coordinate several changes through the table at once for it to work. I already got through it manually so I can't reproduce it right now, but I'll let you know if it comes up again.

For what it's worth, the tracking works really well normally! I think this was an instance of a bud appearing in the midst of a cluster of potential mothers, and the automated tracking kept assigning it to the wrong adjacent cell.

**Comment by ElpadoCan** [comment]
Oh ok, actually sorry, but I saw now that you originally wrote that none of the toolbar functions seem to help.

We tried to solve many edge cases with mother-bud pairing but of course there are other cases that we never encountered.

So if you find one of these cases next time, please do not save the correction and send me the data if you can, I'm really happy to try myself and find the reason why.

We consider cell cycle annotations as our core feature and in theory you should never need to manually edit the annotations. The more edge cases we cover the better it gets.

Also, it should not complain that the newly assigned mother is in G1 because that's exactly what a new mother cell needs to be. 

Anyway, let me know when it happens again, thanks!

**Comment by jordanyx** [comment]
That makes sense! I'll let you know if I run into another example like the aforementioned.

More generally, I can confirm now that the "edit annotations" table doesn't automatically propagate changes to future frames. I've also noticed an issue where it will sometimes have a mother-bud pair where both cells are listed as buds, and there's _no_ error. See below:

![cells](https://user-images.githubusercontent.com/99368623/162857186-ff005047-4d9f-417a-8932-d230bff79c90.PNG)

**Comment by ElpadoCan** [comment]
Hi Jordan, let me answer point by point:

1. You are right, that should be caught and the user should be warned, thanks for finding that! I opened a dedicated issue #31 
2. Yes, edit annotations cannot propagate to future and past frames. It is a very last resort and it should not be used often, otherwise, it means we need to improve on those situations
3. Nice idea, I will add an info button with explanations. Also, separating `Relative ID` and `Relationship `column might help to avoid this confusion? I opened a dedicated issue #32

Here are few tips to speed up the annotation process:

- **Try to correct a wrong mother-bud pairing as soon as possible**. The more you wait the less likely is the automatic propagation to work. This is because the cell that you want to be the correct mother needs to be in G1 for the entire **known duration** of the bud, i.e., it cannot already have a bud assigned to it in the future. This is because automatic propagation will correct all the future G1 frames of the correct mother and it will change them to S/G2/M, but this would cause no G1 frames between this bud and the bud it already has in the future. By **known duration** I mean the frames that you already visited at least once in cell cycle annotation mode (which is also the last frame that can be visited with the slider).
- **When unsure use the second viewer window**. This is where the second viewer window that you can open with the [Eye-plus](https://github.com/SchmollerLab/Cell_ACDC/blob/main/cellacdc/resources/icons/eye-plus.svg) icon comes in handy. Instead of visiting the future frames with the annotation mode, you can check them with viewer window first, just to be prepared of what will happen and to correct as much as possible in the current frame. The viewer window is linked to main GUI, i.e. you can view the frames you want in the viewer, but as soon as you change frame in the main window that the viewer goes back to the current frame and it changes together with the main GUI.

**Comment by ElpadoCan** [comment]
An additional note, I just tested your issue of the two buds (point 2.) but it seems like I cannot replicate it. Please see issue #31 where I tried to replicate, but got warnings. 

I guess that somehow you had that situation from editing annotations in previous frames?

**Comment by jordanyx** [comment]
These are good tips, thanks! And yeah, I probably caused some of the problems myself by going into the table manually. I'll be sure to try all other things before resorting to that going forward! Will let you know if I run into another instance of the uncaught budless mother that's not the result of manual table fidgeting.

**Comment by ElpadoCan** [comment]
See issue #32 for a new feature that can help with this issue

**Comment by jordanyx** [comment]
This is definitely clearer, thanks!

**Comment by ElpadoCan** [comment]
Yes, I agree, we need more documentation, tutorials and examples. We are working on putting that on a web page instead of a PDF manual, I hope we get funded to speed up that process, but it will definitely happen anyway!
