### ISSUE TITLE
"Do not remove annotations" option in seg/track mode

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#33]
Sometimes I notice I made a mistake on a mask of a cell after doing the cell cycle annotations, and go back to change things slightly; for instance, enlarging the cell because I made it too small on accident. This uses the Brush tool, which triggers the warning "You modified a frame that has cell cycle annotations" even when I'm not adding any new cells, merely adjusting an existing mask. It would be nice if there were a way for the software to sense that I haven't made any changes that would impact the cell cycle analysis (creating or removing a cell). Alternatively, perhaps there could be a way to disable the warning temporarily; the user assumes the risk of making changes that may affect cell cycle annotations.

**Comment by ElpadoCan** [comment]
I released `v1.2.4rc16` which has a fix for this issue. Activate the environment and update with `pip install --upgrade cellacdc`

On the dialogue, you can now check the option called "Remember my choice and do not ask again". You can then choose to reset the behaviour and be asked again by going to the `Settings `menu on the top menu bar and checking the specific option.

Let me know if it works, thanks!

**Comment by jordanyx** [comment]
Hi Francesco,

In testing out the fix, the window showed up sometimes even after I'd selected the check box, but then after the 4th or 5th try it stopped popping up. After that it worked fine?

**Comment by ElpadoCan** [comment]
Hi Jordan, that depends on the type of edit. If you add a new mask with the brush and check "Do not show again" you will not be asked again ONLY when adding a new cell with the brush. If instead you for example delete an ID with the middle click you still get asked for that specific edit and you can turn it off with "Do not show again".

The reason why I did it this way is because one can have different choices for each type of edit.

If you prefer to turn off ALL the warnings, you can do that from the `Settings` menu on the top menubar, where you can uncheck all the warnings related to a specific edit. Note that the default action, in that case, is to NOT remove the annotations (since you did not have a chance to choose on the dialogue that you are turning off). However,I am not sure I would do it unless you are sure your edit doesn't break the annotations. 

If instead, you got asked again for the same exact edit (for example adding a new cell with the brush) then it's a bug. Let me know, thanks!
