### ISSUE TITLE
After re-tracking, cell masks get merged automatically?

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#36]
Not sure if this is a bug or just how the ACDC tracking works--after going through and making all the masks look good, I sometimes go back to the start and try to use the retrack function from frame 1. When I go back through the frames, I often get cell masks that were previously separated, merged back into one cell, so then I have to manually separate them again. Is this supposed to happen?

**Comment by ElpadoCan** [comment]
Hi Jordan, I know that this happens with YeaZ tracker but not with Cell-ACDC tracker. However, I never tested to see if it happens also on the original YeaZ tracker. We modified YeaZ tracker to make it faster and suitable for real time tracking and in theory it should work the exact same as the original, just a bit faster. Since you brought it up anyway, leave the issue open and I will do some tests before concluding that it is an issue of the original YeaZ tracker. I will keep you updated, thanks

**Comment by jordanyx** [comment]
Hi Francesco, 
I thought I might have selected the wrong tracker on accident, but I just tested it again and confirmed that it does seem to happen on occasion with the CellACDC tracker. Sometimes it's adjacent cells, and other times it's cells that are quite far from each other. Thankfully it's usually pretty easy to catch and fix (the automatic split cell function is fantastic!), but I thought it was odd so I wanted to point it out.

**Comment by ElpadoCan** [comment]
Oh ok, that is a problem then, thanks for spotting it! Do you have a chance to share a position where it happens? It will be faster to fix it this way, thanks!

**Comment by jordanyx** [comment]
Hi Francesco, an update on this behavior:
It seems it might not be tied to the tracking so much as when I use "apply to all future frames" after changing a mask ID. Am I correct to assume it takes the numerical change in a given frame (e.g. cell 1 becomes cell 2) and propagates that forward? This would explain why in later frames I get cells that appear merged, so it's entirely my fault--sorry about that!

When I do merge cells that way, I also don't get the multiple contours error, which is interesting--not sure if there's some override involved when it's "manually changed" like that?

**Comment by ElpadoCan** [comment]
Yes, your assumption is correct, and it's the reason why one needs to be a bit cautious when propagating changes to future frames.

However, I will add a check on the "apply to all future frames" function to avoid merging. This is actually already in the tracking algorithm because before assigning tracked IDs it first assigns unique IDs to the untracked cells (like new buds). The apply future frames instead, is a bit dumber and doesn't check for that. 

Re-tracking cannot solve the problem because it doesn't automatically split. Having an automatic split could cause over-splitting where it's not needed, so I am not sure what is better in that case.

For the multiple contours error, you should get it only when the merged objects are entirely separated because two touching objects that are merged still have a single contour. Multiple contours are for merged non-touching objects or objects with holes for example (one outer contour and one inner contour for the hole).

Anyway, if you have a Position to share (you can share it to my Google account padovaf@tcd.ie if you don't want to make a public link) I am very happy to test further.

**Comment by ElpadoCan** [comment]
Hi Jordan, I know you said you had merging issues with Cell-ACDC tracker, but I released `v1.2.4-rc.18` where I fixed the merging issues of the YeaZ tracker. 

Let me know if you will have these issues again, thanks!

**Comment by jordanyx** [comment]
Hi Francesco,

I haven't noticed this problem happening since, so I'm guessing it's fixed (and I think I also have been using the correct option for propagating changes). I'll mark it as closed for now, and only reopen if it happens again. Thanks!
