### ISSUE TITLE
Option to select which columns to include in the 'Concatenate acdc output tables' utility

### ISSUE THREAD

**Issue by KurtSchmoller** [SchmollerLab/Cell_ACDC#364]
### Description:

When combining positions with the 'concatenate acdc output tables from multiple positions' utility, it would be useful to be able to produce a table which includes only the columns required for the current analysis.

**Comment by ElpadoCan** [comment]
Hi Kurt, I just implemented this. At some point in the guided process, you will get the window where you can select the measurements you want to have in the final table. 

Since one could potentially save multiple tables(each with a different set of metrics) from the same positions I added that you can append a text at the end of the file name (which can also be empty of course).

Please pull the last version and let me know if it works, thanks!

**Comment by ElpadoCan** [comment]
Hi Kurt, I just added a new section in the "Set measurements" dialog called "Additional columns" where you can select those columns that are not a measurement (like cell_cycle_stage, generation_num, etc.).

Let me know if it works, thanks!

**Comment by KurtSchmoller** [comment]
Thanks
