### ISSUE TITLE
Changes in Brush/Eraser Tools? Delay in screen updating?

### ISSUE THREAD

**Issue by jacobmhkim** [SchmollerLab/Cell_ACDC#44]
I just updated acdc to version 22, and I noticed a change in the brush tool. Previously with the brush tool, it draws the mask of the cell that is in the center of the brush tool circle. However, now it seems to draw the mask of a cell that is not in the center of the circle. 

The eraser tool looks like it has the same problem, but when you actually erase, it erases the cell that's actually in the center, and not the color the circle is. The brush tool doesn't behave this way.

Also, I noticed that sometimes there are delays in the screen updating after using the tool. The brush tool won't update the mask until you let go of the mask. And when you have the eraser tool on and you change frames, the masks don't update until you turn off the eraser tool.

Brush tool problems:
![image](https://user-images.githubusercontent.com/10964296/168668121-4a2ae20c-17fe-4558-ba0b-c7cbd17ef3bf.png)

Eraser Tool problems:
![image](https://user-images.githubusercontent.com/10964296/168668416-75b18164-ef80-47f8-9895-fbed3b97e257.png)
![image](https://user-images.githubusercontent.com/10964296/168668445-002b917f-567f-4c1b-a47f-d436c26c41e2.png)

**Comment by ElpadoCan** [comment]
Hi Jacob,

You are right, we changed the brush/eraser behaviour because I thought it makes more sense to modify the mask touched by the circle but if you prefer the old way I can add a choice in the settings so you choose which behaviour you want.

For the eraser behaviour instead you are right I didn't realise that it was still erasing in the center instead of the touching ID (if it is touching two IDs then it chooses the highest ID but actually it should choose the one that has the highest number of pixels in the circle?). Anyway that's a bug and I will fix it.

For the delay I will do some tests because I didn't see that behaviour.

For the problem with updating the mask with the active eraser that should have been fixed in the latest release because Jordan actually already reported it and he said it's fixed? See issue #42, can you actually double check you have v22? It should be written both on the terminal when you launch cell-acdc or from the `Help --> About` menu on the top of the main launcher.

Thanks and I will keep you updated.

**Comment by jacobmhkim** [comment]
I prefer the old way because when I draw a new bud, I just use the brush tool to create a partial circle off the mother. But with this update, I can't create a new cell id this way.

![image](https://user-images.githubusercontent.com/10964296/168681050-9ed1b094-3736-4d2f-896b-869233b79a12.png)

**Comment by jacobmhkim** [comment]
and yes, the update fixed the eraser mask problem.

**Comment by jacobmhkim** [comment]
I would prefer if both the brush and eraser tools had an option to revert to the original setting of choosing the mask in the center of the circle.

**Comment by ElpadoCan** [comment]
Absolutely no problem, I will add a setting that you can toggle. The setting will be saved and you will not have to change it anymore (unless you want the other mode of course)

**Comment by ElpadoCan** [comment]
So I released `v1.2.4rc23` where the GUI has a  new option in the `Settings` menu called `Brush/eraser cursor hovering mode` and the default now is to use the centre of the circle, like in previous releases. Update with `pip install --upgrade cellacdc`. Let me know if it works, thanks!

**Comment by jacobmhkim** [comment]
Thanks it works!
