### ISSUE TITLE
How to convert npz to COCO format

### ISSUE THREAD

**Issue by ptlzon** [SchmollerLab/Cell_ACDC#510]
### Description:

I'm sorry for the naive question.
Is this already implemented?
How can I convert .npz to COCO format?

**Comment by ElpadoCan** [comment]
Hi @ptlzon,

Unfortunately, it is not implemented yet. Do you need it for training purposes? Do you want to convert the segmentation files to `instances_train.json` and `instances_val.json` only or do you need the full COCO format with also paths to the images?

Because with the full COCO format, you would also need to split the frames into single images.  You will also have to decide on fields like `supercategory`, `id`, and `name`.

It's doable, but I think it is very user-specific. If you are familiar with Python and you write some kind of function that converts segmentation files to JSON annotations I can then help to integrate it into Cell-ACDC. Let me know what you think about it, thanks! 

Best,
Francesco
