### ISSUE TITLE
Deletion box in GUI doesn't work

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#60]
**Describe the bug**
In the GUI, the tool that lets you draw a box to automatically delete all cells touching it doesn't appear to be working (icon below).

![Capture](https://user-images.githubusercontent.com/99368623/173465022-32d6d7a3-023b-4d00-ae37-25525c328edd.PNG)

Windows 10, Python 3.9.6, ACDC v1.2.4rc26

**Comment by ElpadoCan** [comment]
Hi Jordan, are you trying to add the deletion box while the right image (the image with the segmentation mask) is hidden? Because I just realised now that it would not work, because the deletion box is added only to the right image.  When the right image is hidden there is nothing to add a box to.

I will fix it in the next release, sorry about that.

**Comment by jordanyx** [comment]
Ah! That's probably the reason then--I was working exclusively off the left window and had the right closed so I could look at something in FIJI at the same time. Works fine now, thanks!
