### ISSUE TITLE
GUI doesn't open

### ISSUE THREAD

**Issue by MasaruShimasawa** [SchmollerLab/Cell_ACDC#82]
**Describe the bug**

I can't launch GUI.

**To Reproduce**
1. Go to acdc.
2. Click on 3. launch GUI.
3. See error

**Expected behavior**
GUI doesn't open and you will see the following error in your terminal
------------------------------------------------------------------------------------------------
Opening GUI...
Initializing GUI v1.2.4rc29...
Traceback (most recent call last):
  File "/Users/name/opt/anaconda3/envs/acdc/lib/python3.9/site-packages/cellacdc/__main__.py", line 579, in launchGui
    self.guiWin.run()
  File "/Users/name/opt/anaconda3/envs/acdc/lib/python3.9/site-packages/cellacdc/gui.py", line 1144, in run
    self.gui_createMenuBar()
  File "/Users/name/opt/anaconda3/envs/acdc/lib/python3.9/site-packages/cellacdc/gui.py", line 1334, in gui_createMenuBar
    fontActionGroup.setExclusionPolicy(
AttributeError: 'QActionGroup' object has no attribute 'setExclusionPolicy'
------------------------------------------------------------------------------------------------

**Screenshots**

**Desktop (please complete the following information):**
 - Python version: Python 3.9.7
 - OS: macOS Monterey version 12.4
 - Cell-ACDC Version 1.2.4rc29
 
**Additional context**
I recently updated anaconda navigator (2.2.0).

**Comment by MasaruShimasawa** [comment]
I also had installed spyder in the acdc venv using the anaconda navigator

**Comment by MasaruShimasawa** [comment]
We resolved this issue by the following steps.

1. conda create -n acdc python=3.9
(2. IF YOU GET BROTLI ERROR: conda install -c anaconda urllib3)
3. pip install acdc 
4. pip install --upgrade cell acdc

Then we were able to open acdc and its GUI.

**Comment by ElpadoCan** [comment]
Hi @MasaruShimasawa happy to hear that you solve the issue.

I just have a couple of comments:

1. You could probably solve the brotli error issue with the command `conda update conda` since it could be an old bug of conda.
2. The `acdc` package is not needed. This package is simply called similar to cellacdc unfortunately.

The error is weird anyway, `QActionGroup` is a Qt 5 widget (the library that is used for the GUI elements) that has that attribute only starting from Qt version 5.14, so the easier fix could have been `pip install --upgrade PyQt5` to get the latest version of Qt for python.

Anyway thanks for the useful info! Cheers, Francesco

**Comment by ElpadoCan** [comment]
I'm closing this since it sounds like it was solved. Feel free to reopen it or create a new issue, thanks!
