### ISSUE TITLE
Data prep module: minor UI bug

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#96]
Very minor thing I noticed--if you close the crop/save window using "cancel" or the X at the top right, it still shows the green dialogue box saying it's done and you can close the position. This might be misleading if a user chooses to cancel without saving.

**Comment by ElpadoCan** [comment]
Hi Jordan, the reason why it says "Done" is because if, for example, you aligned data that step was already saved and when you hit "cancel" on that dialogue then it skips the cropping and it tells you that you are done (since alignment was already saved). 

However, I will change that message to something clearer, like "Alignment done, cropping cancelled" or something like this. Thanks for pointing that out!

**Comment by jordanyx** [comment]
Oh I see, thanks for the clarification, that makes sense!
